// --- Interfaces ---

interface ResourceInfo {
  name: string;
  type: string;
}

interface WorldPowerLevels {
  [theaterId: string]: {
    [zoneName: string]: number;
  };
}

// --- Data Mappings ---
// Mythic Lead Identifiers (Base item type names)
export const MYTHIC_LEAD_IDENTIFIERS: Set<string> = new Set([
  "managerdoctor_sr_kingsly",
  "managerdoctor_sr_noctor",
  "managerdoctor_sr_treky",
  "managerengineer_sr_countess",
  "managerengineer_sr_maths",
  "managerengineer_sr_sobs",
  "managerexplorer_sr_birdie",
  "managerexplorer_sr_eagle",
  "managerexplorer_sr_spacebound",
  "managergadgeteer_sr_fixer",
  "managergadgeteer_sr_flak",
  "managergadgeteer_sr_zapps",
  "managerinventor_sr_frequency",
  "managerinventor_sr_rad",
  "managerinventor_sr_square",
  "managermartialartist_sr_dragon",
  "managermartialartist_sr_samurai",
  "managermartialartist_sr_tiger",
  "managersoldier_sr_malcolm",
  "managersoldier_sr_princess",
  "managersoldier_sr_ramsie",
  "managertrainer_sr_jumpy",
  "managertrainer_sr_raider",
  "managertrainer_sr_yoglattes",
]);

// Resource Mapping (Item Type Base Name -> Display Name & Category)
export const RESOURCE_MAP: Record<string, ResourceInfo> = {
  // Survivors / People
  workerbasic_sr_t01: { name: "Legendary Survivor", type: "survivor" },
  reagent_people: { name: "Training Manual", type: "evo" },
  reagent_promotion_survivors: { name: "Survivor Supercharger", type: "sc" },
  voucher_generic_worker_r: { name: "Rare Survivor Token", type: "token" },
  voucher_generic_worker_vr: { name: "Epic Survivor Token", type: "token" },
  voucher_generic_worker_sr: {
    name: "Legendary Survivor Token",
    type: "token",
  },
  voucher_generic_manager_r: {
    name: "Rare Lead Survivor Token",
    type: "token",
  },
  voucher_generic_manager_vr: {
    name: "Epic Lead Survivor Token",
    type: "token",
  },
  voucher_generic_manager_sr: {
    name: "Legendary Lead Survivor Token",
    type: "token",
  },

  // XP
  heroxp: { name: "Hero XP", type: "xp" },
  schematicxp: { name: "Schematic XP", type: "xp" },
  personnelxp: { name: "Survivor XP", type: "xp" },
  phoenixxp: { name: "Venture XP", type: "xp" },
  phoenixxp_reward: { name: "Venture XP", type: "xp" },
  smallxpboost: { name: "XP Boost", type: "xpboost" },
  smallxpboost_gift: { name: "Teammate XP Boost", type: "xpboost" },

  // Evolution Materials & Flux
  reagent_c_t01: { name: "Pure Drop of Rain", type: "evo" },
  reagent_c_t02: { name: "Lightning in a Bottle", type: "evo" },
  reagent_c_t03: { name: "Eye of the Storm", type: "evo" },
  reagent_c_t04_veryhigh: { name: "Good Shard", type: "evo" },
  reagent_c_t04_high: { name: "Bad Shard", type: "evo" },
  reagent_c_t04: { name: "Storm Shard", type: "evo" },
  reagent_evolverarity_r: { name: "Rare Flux", type: "evo" },
  reagent_evolverarity_vr: { name: "Epic Flux", type: "evo" },
  reagent_evolverarity_sr: { name: "Legendary Flux", type: "evo" },
  reagent_traps: { name: "Trap Designs", type: "evo" },
  reagent_weapons: { name: "Weapon Designs", type: "evo" },

  // Superchargers
  reagent_promotion_heroes: { name: "Hero Supercharger", type: "sc" },
  reagent_promotion_traps: { name: "Trap Supercharger", type: "sc" },
  reagent_promotion_weapons: { name: "Weapon Supercharger", type: "sc" },

  // Perk Materials
  reagent_alteration_gameplay_generic: { name: "Core RE-PERK!", type: "perk" },
  reagent_alteration_generic: { name: "RE-PERK!", type: "perk" },
  reagent_alteration_ele_nature: { name: "AMP UP", type: "perk" },
  reagent_alteration_ele_fire: { name: "FIRE UP", type: "perk" },
  reagent_alteration_ele_water: { name: "FROST UP", type: "perk" },
  reagent_alteration_upgrade_uc: { name: "Uncommon PERK-UP!", type: "perk" },
  reagent_alteration_upgrade_r: { name: "Rare PERK-UP!", type: "perk" },
  reagent_alteration_upgrade_vr: { name: "Epic PERK-UP!", type: "perk" },
  reagent_alteration_upgrade_sr: { name: "Legendary PERK-UP!", type: "perk" },

  // Currencies
  eventcurrency_scaling: { name: "Gold", type: "currency" },
  eventscaling: { name: "Gold", type: "currency" },
  currency_mtxswap: { name: "V-Bucks", type: "currency" },
  currency_xrayllama: { name: "X-Ray Tickets", type: "currency" },
  specialcurrency_daily: { name: "Daily Coins", type: "currency" },
  eventcurrency_founders: { name: "Founder's Coins", type: "currency" },
  campaign_event_currency: { name: "Event Tickets", type: "currency" },
  eventcurrency_adventure: { name: "Adventure Tickets", type: "currency" },
  eventcurrency_blockbuster: { name: "Blockbuster Tickets", type: "currency" },
  eventcurrency_candy: { name: "Candy", type: "currency" },
  eventcurrency_lunar: { name: "Lunar Tickets", type: "currency" },
  eventcurrency_roadtrip: { name: "Road Trip Tickets", type: "currency" },
  eventcurrency_snowballs: { name: "Snowflake Tickets", type: "currency" },
  eventcurrency_spring: { name: "Spring Tickets", type: "currency" },
  eventcurrency_summer: { name: "Summer Tickets", type: "currency" },

  // Vouchers & Tokens
  voucher_herobuyback: { name: "Hero Recruitment Voucher", type: "voucher" },
  voucher_item_buyback: { name: "Weapon Research Voucher", type: "voucher" },
  voucher_basicpack: { name: "Mini Llama", type: "token" },
  voucher_cardpack_bronze: { name: "Upgrade Llama", type: "token" },
  voucher_cardpack_jackpot: { name: "Jackpot Llama", type: "token" },
  voucher_generic_hero_r: { name: "Rare Hero Token", type: "token" },
  voucher_generic_hero_vr: { name: "Epic Hero Token", type: "token" },
  voucher_generic_hero_sr: { name: "Legendary Hero Token", type: "token" },

  // Construction Materials
  wooditemdata: { name: "Wood", type: "construction" },
  stoneitemdata: { name: "Stone", type: "construction" },
  metalitemdata: { name: "Metal", type: "construction" },

  // Ingredients
  bacon: { name: "Bacon", type: "ingredients" },
  batteries: { name: "Batteries", type: "ingredients" },
  blast_powder: { name: "Blast Powder", type: "ingredients" },
  crystal_quartz: { name: "Quartz Crystal", type: "ingredients" },
  duct_tape: { name: "Duct Tape", type: "ingredients" },
  flowers: { name: "Flowers", type: "ingredients" },
  herbs: { name: "Fibrous Herbs", type: "ingredients" },
  nuts_bolts: { name: "Nuts 'n' Bolts", type: "ingredients" },
  ore_alloy: { name: "Rough Ore", type: "ingredients" },
  ore_coal: { name: "Coal", type: "ingredients" },
  improvised: { name: "Rotating Gizmo", type: "ingredients" },
  rare_mechanism: { name: "Rotating Gizmo", type: "ingredients" },
  rare_powercell: { name: "Active Powercell", type: "ingredients" },
  resin: { name: "Adhesive Resin", type: "ingredients" },
  mechanical_parts_t01: { name: "Rusty Mechanical Parts", type: "ingredients" },
  mechanical_parts_t02: {
    name: "Simple Mechanical Parts",
    type: "ingredients",
  },
  mechanical_parts_t03: {
    name: "Sturdy Mechanical Parts",
    type: "ingredients",
  },
  mechanical_parts_t04: { name: "Sleek Mechanical Parts", type: "ingredients" },
  mechanical_parts_t05: {
    name: "Efficient Mechanical Parts",
    type: "ingredients",
  },
  mechanical_parts_t06: {
    name: "Vindertech Mechanical Parts",
    type: "ingredients",
  },
  ore_copper: { name: "Copper Ore", type: "ingredients" },
  ore_silver: { name: "Silver Ore", type: "ingredients" },
  ore_malachite: { name: "Malachite Ore", type: "ingredients" },
  ore_obsidian: { name: "Obsidian Ore", type: "ingredients" },
  crystal_shadowshard: { name: "Shadowshard Ore", type: "ingredients" },
  ore_brightcore: { name: "Brightcore Ore", type: "ingredients" },
  crystal_sunbeam: { name: "Sunbeam Crystal", type: "ingredients" },
  powder_t01: { name: "Rough Mineral Powder", type: "ingredients" },
  powder_t02: { name: "Simple Mineral Powder", type: "ingredients" },
  powder_t03: { name: "Fine-grain Mineral Powder", type: "ingredients" },
  powder_t04: { name: "Chat-black Mineral Powder", type: "ingredients" },
  powder_t05: { name: "Oxidized Mineral Powder", type: "ingredients" },
  powder_t06: { name: "Spectral Mineral Powder", type: "ingredients" },
  ore_spectrolite: { name: "Spectrolite Ore", type: "ingredients" },
  crystal_moonglow: { name: "Moonglow Crystal", type: "ingredients" },
  crystal_rainbow: { name: "Rainbow Crystal", type: "ingredients" },
  honey: { name: "Honey", type: "ingredients" },

  // Other Meta Items
  mythic_lead_survivor: { name: "Mythic Lead Survivor", type: "survivor" },
  workerbasic_vr: { name: "Epic Survivor", type: "survivor" },
  did_defender: { name: "Defender", type: "defender" },
  hid_ninja: { name: "Ninja", type: "hero" },
  hid_outlander: { name: "Outlander", type: "hero" },
  hid_soldier: { name: "Soldier", type: "hero" },
  hid_constructor: { name: "Constructor", type: "hero" },
  hid_commando: { name: "Soldier", type: "hero" },
  "schematic:sid": { name: "Schematic", type: "schematic" },
  double_legendary_schematic: {
    name: "Double Legendary Schematics",
    type: "schematic",
  },
  legendary_trap: { name: "Legendary", type: "schematic" },
};

// --- Trap Mappings ---
export const TRAP_MAP: Record<string, ResourceInfo> = {
  sid_ceiling_electric_aoe: { name: "Ceiling Electric Field", type: "trap" },
  sid_ceiling_electric_single: { name: "Ceiling Zapper", type: "trap" },
  sid_ceiling_falling: { name: "Ceiling Drop Trap", type: "trap" },
  sid_ceiling_gas: { name: "Ceiling Gas Trap", type: "trap" },
  sid_floor_campfire: { name: "Cozy Campfire", type: "trap" },
  sid_floor_flamegrill: { name: "Flame Grill Floor Trap", type: "trap" },
  sid_floor_freeze: { name: "Floor Freeze Trap", type: "trap" },
  sid_floor_health: { name: "Healing Pad", type: "trap" },
  sid_floor_launcher: { name: "Floor Launcher", type: "trap" },
  sid_floor_spikes_wood: { name: "Wooden Floor Spikes", type: "trap" },
  sid_floor_spikes: { name: "Retractable Floor Spikes", type: "trap" },
  sid_floor_tar: { name: "Tar Pit", type: "trap" },
  sid_floor_ward: { name: "Anti-Air Trap", type: "trap" },
  sid_wall_cannons: { name: "Broadside", type: "trap" },
  sid_wall_darts: { name: "Wall Darts", type: "trap" },
  sid_wall_electric: { name: "Wall Dynamo", type: "trap" },
  sid_wall_launcher: { name: "Wall Launcher", type: "trap" },
  sid_wall_light: { name: "Wall Lights", type: "trap" },
  sid_wall_speaker: { name: "Sound Wall", type: "trap" },
  sid_wall_wood_spikes: { name: "Wall Spikes", type: "trap" },
};

// --- Hero Mappings ---
export const HERO_MAP: Record<string, ResourceInfo> = {
  cid_commando_007hw: { name: "Ghoul Trooper Ramirez", type: "hero" },
  cid_commando_007hw_rs01: { name: "Brainiac Jonesy", type: "hero" },
  cid_commando_010_bday: { name: "Birthday Brigade Ramirez", type: "hero" },
  cid_commando_011_f_v1_roadtrip: { name: "Redline Ramirez", type: "hero" },
  cid_commando_011_m: { name: "Buckshot Raptor", type: "hero" },
  cid_commando_011_m_easter: { name: "Rabbit Raider Jonesy", type: "hero" },
  cid_commando_013_stpatricks_f_v1: { name: "Four Leaf Wildcat", type: "hero" },
  cid_commando_013_stpatricks_f_v2: {
    name: "Highland Warrior Wildcat",
    type: "hero",
  },
  cid_commando_013_stpatricks_m: { name: "Battle Hound Jonesy", type: "hero" },
  cid_commando_014_m: { name: "Berserker Renegade", type: "hero" },
  cid_commando_014_wukong: { name: "Wukong", type: "hero" },
  cid_commando_015_f_v1_blockbuster: { name: "Chromium Ramirez", type: "hero" },
  cid_commando_015_m_v1_blockbuster: { name: "Diecast Jonesy", type: "hero" },
  cid_commando_016_f_v1: { name: "Double Agent Evelynn", type: "hero" },
  cid_commando_016_m_v1: { name: "Undercover Vaughn", type: "hero" },
  cid_commando_017_f_v1: { name: "First Shot Rio", type: "hero" },
  cid_commando_018: { name: "Quickdraw Calamity", type: "hero" },
  cid_commando_019: { name: "Steel Wool Carlos", type: "hero" },
  cid_commando_021: { name: "Liteshow Spitfire", type: "hero" },
  cid_commando_022: { name: "Archetype Havoc", type: "hero" },
  cid_commando_023: { name: "Jolly Headhunter", type: "hero" },
  cid_commando_024: { name: "Sgt. Winter", type: "hero" },
  cid_commando_025: { name: "Crackshot", type: "hero" },
  cid_commando_026: { name: "Fallen Love Ranger Jonesy", type: "hero" },
  cid_commando_027_piratesoldier: { name: "Buccaneer Jonesy", type: "hero" },
  cid_commando_028_bunnybrawler: { name: "Bunny Brawler Luna", type: "hero" },
  cid_commando_030_retroscifisoldier: {
    name: "Extraterrestrial Rio",
    type: "hero",
  },
  cid_commando_031_radsoldier: { name: "Breakbeat Wildcat", type: "hero" },
  cid_commando_032_halloweensoldier: { name: "JONESEE-BOT", type: "hero" },
  cid_commando_033_halloweenquestsoldier: {
    name: "Swamp Knight",
    type: "hero",
  },
  cid_commando_038_shock_wave: { name: "Powerhouse", type: "hero" },
  cid_commando_039_pajama_party: { name: "Tricera Ops Ramirez", type: "hero" },
  cid_commando_040_pirate_br: { name: "Buccaneer Ramirez", type: "hero" },
  cid_commando_041_pirate_02_br: { name: "Sea Wolf Jonesy", type: "hero" },
  cid_commando_042_major: { name: "Major Oswald", type: "hero" },
  cid_commando_044_gumshoe_dark: { name: "Noir", type: "hero" },
  cid_commando_045_chaos_agent: { name: "Chaos Agent", type: "hero" },
  cid_commando_046_forestqueen: { name: "Autumn Queen", type: "hero" },
  cid_commando_047_prickly_patroller: {
    name: "Prickly Patroller Ramirez",
    type: "hero",
  },
  cid_commando_gcgrenade_t: { name: "Sub Commando Jonesy", type: "hero" },
  cid_commando_grenadegun_m_t: { name: "Rescue Trooper Havoc", type: "hero" },
  cid_commando_gunheadshothw: { name: "Skull Trooper Jonesy", type: "hero" },
  cid_commando_gunheadshothw_rs01: {
    name: "Skull Ranger Ramirez",
    type: "hero",
  },
  cid_commando_gunheadshot_m_v1_roadtrip: {
    name: "Tactical Assault Sledgehammer",
    type: "hero",
  },
  cid_commando_guntough_f_4thjuly: {
    name: "Star-Spangled Headhunter",
    type: "hero",
  },
  cid_commando_guntough_m_4thjuly: {
    name: "Stars and Stripes Jonesy",
    type: "hero",
  },
  cid_commando_guntough_rs01: { name: "Birthday Brigade Jonesy", type: "hero" },
  cid_commando_guntough_valentine: { name: "Love Ranger Jonesy", type: "hero" },
  cid_commando_myth02: { name: "Raven", type: "hero" },
  cid_commando_myth03: { name: "Carbide", type: "hero" },
  cid_commando_shockdamage: { name: "Shock Trooper Renegade", type: "hero" },
  cid_commando_sony: { name: "Commando Ramirez", type: "hero" },
  cid_commando_xbox: { name: "Commando Renegade", type: "hero" },
  cid_constructor_007hw: { name: "Kyle the 13th", type: "hero" },
  cid_constructor_008_foundersf: { name: "Power B.A.S.E. Penny", type: "hero" },
  cid_constructor_008_foundersm: { name: "Power B.A.S.E. Kyle", type: "hero" },
  cid_constructor_011_f_v1_roadtrip: { name: "Thunder Thora", type: "hero" },
  cid_constructor_014: { name: "Riot Response Hazard", type: "hero" },
  cid_constructor_014_f: { name: "Riot Control Izza", type: "hero" },
  cid_constructor_016_f_v1: { name: "Demolitionist Penny", type: "hero" },
  cid_constructor_016_m_v1: { name: "Saboteur Bull", type: "hero" },
  cid_constructor_016_m_v1_blockbuster: { name: "8-Bit Demo", type: "hero" },
  cid_constructor_017_f_v1: { name: "Vintage-Tech Penny", type: "hero" },
  cid_constructor_018: { name: "Black Knight Garridan", type: "hero" },
  cid_constructor_019: { name: "Sentry Gunner Airheart", type: "hero" },
  cid_constructor_020: { name: "Sentry Gunner Krampus", type: "hero" },
  cid_constructor_021: { name: "Dark Vanguard Airheart", type: "hero" },
  cid_constructor_022: { name: "Conqueror Magnus", type: "hero" },
  cid_constructor_023: { name: "The Ice King", type: "hero" },
  cid_constructor_025_progressivepirateconstructor: {
    name: "Blakebeard The Blackhearted",
    type: "hero",
  },
  cid_constructor_026_bombsquadconstructor: {
    name: "BombSquad Kyle",
    type: "hero",
  },
  cid_constructor_027_dinoconstructor: {
    name: "Prehistoric Izza",
    type: "hero",
  },
  cid_constructor_028_retroscificonstructor: { name: "ED-EE", type: "hero" },
  cid_constructor_029_radstoryconstructor: { name: "Dennis Jr.", type: "hero" },
  cid_constructor_030_radconstructor: { name: "Power Pop Penny", type: "hero" },
  cid_constructor_031_halloweenconstructor: {
    name: "'Arrlene' Izza",
    type: "hero",
  },
  cid_constructor_032_toyconstructor: {
    name: "Sgt. Tank Gatling",
    type: "hero",
  },
  cid_constructor_033_villain_fleming: { name: "Gold Knox", type: "hero" },
  cid_constructor_034_mechstructor: { name: "Machinist Mina", type: "hero" },
  cid_constructor_035_birthday_constructor: {
    name: "Birthday Brigade Penny",
    type: "hero",
  },
  cid_constructor_036_dinoconstructor: { name: "Ankylo Kyle", type: "hero" },
  cid_constructor_037_director: { name: "Director Riggs", type: "hero" },
  cid_constructor_038_gumshoe: { name: "Sleuth", type: "hero" },
  cid_constructor_039_assemble_l: { name: "Lok-Bot", type: "hero" },
  cid_constructor_040_lars: { name: "Lars", type: "hero" },
  cid_constructor_041_alienagent: { name: "Brainstorm", type: "hero" },
  cid_constructor_042_butterfly: { name: "Flutter", type: "hero" },
  cid_constructor_043_hotwire: { name: "Hotwire", type: "hero" },
  cid_constructor_basebig: { name: "MEGA B.A.S.E. Kyle", type: "hero" },
  cid_constructor_basehyper: { name: "Hotfixer Hazard", type: "hero" },
  cid_constructor_basehyperhw: { name: "Catstructor Penny", type: "hero" },
  cid_constructor_hammerplasma: { name: "Electro-pulse Penny", type: "hero" },
  cid_constructor_hammerplasma_4thjuly: { name: "Patriot Penny", type: "hero" },
  cid_constructor_hammertank: { name: "Tank Penny", type: "hero" },
  cid_constructor_myth02: { name: "Steel Wool Syd", type: "hero" },
  cid_constructor_plasmadamage: {
    name: "Plasma Specialist Izza",
    type: "hero",
  },
  cid_constructor_plasmadamage_easter: {
    name: "Miss Bunny Penny",
    type: "hero",
  },
  cid_constructor_rushbase: { name: "B.A.S.E. Kyle", type: "hero" },
  cid_constructor_rushbase_f: { name: "Marathon Hype", type: "hero" },
  cid_constructor_sony: { name: "Guardian Penny", type: "hero" },
  cid_constructor_xbox: { name: "Guardian Knox", type: "hero" },
  cid_ninja_009_f_valentine: { name: "Snuggle Specialist Sarah", type: "hero" },
  cid_ninja_010: { name: "Deadly Star Scorpion", type: "hero" },
  cid_ninja_010_f: { name: "Deadly Blade Crash", type: "hero" },
  cid_ninja_013: { name: "Alchemist Sarah", type: "hero" },
  cid_ninja_014: { name: "Whirlwind Scorch", type: "hero" },
  cid_ninja_014_f: { name: "Thunderstrike Mari", type: "hero" },
  cid_ninja_015_f_v1_roadtrip: { name: "Whiteout Fiona", type: "hero" },
  cid_ninja_017_m_v1: { name: "Infiltrator Ken", type: "hero" },
  cid_ninja_018: { name: "Plague Doctor Igor", type: "hero" },
  cid_ninja_019: { name: "Dire", type: "hero" },
  cid_ninja_020: { name: "Cloaked Shadow", type: "hero" },
  cid_ninja_021: { name: "Forged Fate", type: "hero" },
  cid_ninja_022: { name: "Overtaker Hiro", type: "hero" },
  cid_ninja_023: { name: "Lynx Kassandra", type: "hero" },
  cid_ninja_024: { name: "Anti-Cuddle Sarah", type: "hero" },
  cid_ninja_025_pirateninja: { name: "Swashbuckler Keelhaul", type: "hero" },
  cid_ninja_026_reddragonninja: { name: "Hybrid", type: "hero" },
  cid_ninja_027_bunnyninja: { name: "Dashing Hare Ken", type: "hero" },
  cid_ninja_028_razor: { name: "Razor", type: "hero" },
  cid_ninja_029_dinoninja: { name: "Paleo Luna", type: "hero" },
  cid_ninja_030_retroscifininja: { name: "Intergalactic Ken", type: "hero" },
  cid_ninja_031_radninja: { name: "Varsity Hiro", type: "hero" },
  cid_ninja_033_halloweenninja: { name: "Mermonster Ken", type: "hero" },
  cid_ninja_034_toymonkey: { name: "Monks", type: "hero" },
  cid_ninja_035_f_cupid: { name: "Stoneheart Farrah", type: "hero" },
  cid_ninja_037_junk_samurai: { name: "Samurai Scrapper", type: "hero" },
  cid_ninja_038_male_ninja_pirate: { name: "Freebooter Ken", type: "hero" },
  cid_ninja_039_dino_ninja: { name: "Jurassic Ken", type: "hero" },
  cid_ninja_040_dennis: { name: "Dennis", type: "hero" },
  cid_ninja_041_deco: { name: "Venturion", type: "hero" },
  cid_ninja_042_assemble_r: { name: "Robo-Ray", type: "hero" },
  cid_ninja_043_cranium: { name: "Deimos", type: "hero" },
  cid_ninja_044_fennix: { name: "Fennix", type: "hero" },
  cid_ninja_045_snowstrike: { name: "Snowstrike", type: "hero" },
  cid_ninja_048_eternalwanderer: { name: "Eternal Wanderer", type: "hero" },
  cid_ninja_myth02: { name: "The Cloaked Star", type: "hero" },
  cid_ninja_myth03: { name: "Bladestorm Enforcer", type: "hero" },
  cid_ninja_slashbreath: { name: "Dragon Scorch", type: "hero" },
  cid_ninja_slashbreathhw: { name: "Sarah Hotep", type: "hero" },
  cid_ninja_slashtail: { name: "Fleetfoot Ken", type: "hero" },
  cid_ninja_smokedimmak: { name: "Dim Mak Mari", type: "hero" },
  cid_ninja_sony: { name: "Bluestreak Ken", type: "hero" },
  cid_ninja_starsassassin: { name: "Assassin Sarah", type: "hero" },
  cid_ninja_starsassassin_foundersf: {
    name: "Lotus Assassin Sarah",
    type: "hero",
  },
  cid_ninja_starsassassin_foundersm: {
    name: "Lotus Assassin Ken",
    type: "hero",
  },
  cid_ninja_starsrain: { name: "Shuriken Master Sarah", type: "hero" },
  cid_ninja_starsrainhw: { name: "Swift Shuriken Llamurai", type: "hero" },
  cid_ninja_swordmaster: { name: "Swordmaster Ken", type: "hero" },
  cid_ninja_test: { name: "Jade Assassin Sarah", type: "hero" },
  cid_ninja_xbox: { name: "Jade Assassin Sarah", type: "hero" },
  cid_outlander_007_rs01: { name: "Jingle Jess", type: "hero" },
  cid_outlander_008_foundersf: { name: "Recon Scout Jess", type: "hero" },
  cid_outlander_008_foundersm: { name: "Recon Scout A.C.", type: "hero" },
  cid_outlander_010: { name: "Shockblaster Buzz", type: "hero" },
  cid_outlander_010_m: { name: "Trailblaster A.C.", type: "hero" },
  cid_outlander_013_stpatricks: { name: "Staredown Southie", type: "hero" },
  cid_outlander_014: { name: "Fireflower Eagle Eye", type: "hero" },
  cid_outlander_014_m: { name: "Flash A.C.", type: "hero" },
  cid_outlander_018: { name: "Sanguine Dusk", type: "hero" },
  cid_outlander_020: { name: "Valkyrie Rio", type: "hero" },
  cid_outlander_021: { name: "Ventura Ramirez", type: "hero" },
  cid_outlander_022: { name: "Subzero Zenith", type: "hero" },
  cid_outlander_023: { name: "The Ice Queen", type: "hero" },
  cid_outlander_024: { name: "Steel Wool Anthony", type: "hero" },
  cid_outlander_025_pirateoutlander: {
    name: "Crossbones Barret",
    type: "hero",
  },
  cid_outlander_026_bunnyoutlander: {
    name: "Cottontail Eagle Eye",
    type: "hero",
  },
  cid_outlander_027_dinooutlander: { name: "Fossil Southie", type: "hero" },
  cid_outlander_028_retroscifistoryoutlander: {
    name: "Azalea Clark",
    type: "hero",
  },
  cid_outlander_029_retroscifioutlander: { name: "Cyberclops", type: "hero" },
  cid_outlander_030_radoutlander: { name: "Main Stage Quinn", type: "hero" },
  cid_outlander_031_halloweenoutlander: { name: "Willow", type: "hero" },
  cid_outlander_032_toyoutlander: { name: "Jilly Teacup", type: "hero" },
  cid_outlander_033_kurohomura: { name: "Kurohomura", type: "hero" },
  cid_outlander_034_period_fleming: { name: "Undercover Buzz", type: "hero" },
  cid_outlander_035_palespooky_outlander_holiday: {
    name: "Red Willow",
    type: "hero",
  },
  cid_outlander_036_dino_outlander: { name: "Parasaur Jess", type: "hero" },
  cid_outlander_037_fuzzy_bear_teddy: {
    name: "Metal Team Leader",
    type: "hero",
  },
  cid_outlander_038_clip: { name: "Cassie 'Clip' Lipman", type: "hero" },
  cid_outlander_039_female_gumshoe: { name: "Gumshoe", type: "hero" },
  cid_outlander_040_assemblek: { name: "Robo-Kevin", type: "hero" },
  cid_outlander_042_madcap: { name: "Madcap", type: "hero" },
  cid_outlander_043_madcommander: { name: "Mayhem", type: "hero" },
  cid_outlander_myth02: { name: "Ragnarok", type: "hero" },
  cid_outlander_myth03: { name: "Field Agent Rio", type: "hero" },
  cid_outlander_punchdamage: { name: "Striker A.C.", type: "hero" },
  cid_outlander_punchphase: { name: "Shock Specialist A.C.", type: "hero" },
  cid_outlander_sony: { name: "Trailblazer A.C.", type: "hero" },
  cid_outlander_spherefragment: { name: "Trailblazer Quinn", type: "hero" },
  cid_outlander_xbox: { name: "Trailblazer Jess", type: "hero" },
  cid_outlander_zonefragment: { name: "Phase Scout Jess", type: "hero" },
  cid_outlander_zoneharvest: { name: "Pathfinder Jess", type: "hero" },
  cid_outlander_zoneharvest_blockbuster: {
    name: "Archaeolo-Jess",
    type: "hero",
  },
  cid_outlander_zoneharvesthw: { name: "Bloodfinder A.C.", type: "hero" },
  cid_outlander_zonepistol: { name: "Ranger Deadeye", type: "hero" },
  cid_outlander_zonepistolhw: { name: "Beetlejess", type: "hero" },
  cid_commando_009: { name: "Colonel Wildcat", type: "hero" },
  cid_commando_011: { name: "Shrapnel Headhunter", type: "hero" },
  cid_commando_014: { name: "Onslaught Headhunter", type: "hero" },
  cid_commando_029_dinosoldier: { name: "Rex Jonesy", type: "hero" },
  cid_commando_034_toytinkerer: { name: "Ted", type: "hero" },
  cid_commando_035_caped_valentine: { name: "Dashing Hawk", type: "hero" },
  cid_constructor_009: { name: "Sentinel Hype", type: "hero" },
  cid_constructor_010: { name: "Guardian Bull", type: "hero" },
  cid_constructor_011: { name: "Machinist Harper", type: "hero" },
  cid_constructor_013: { name: "Warden Kyle", type: "hero" },
  cid_constructor_015: { name: "Heavy B.A.S.E. Kyle", type: "hero" },
  cid_constructor_024_pirateconstructor: {
    name: "Privateer Hype",
    type: "hero",
  },
  cid_ninja_007: { name: "Brawler Luna", type: "hero" },
  cid_ninja_008: { name: "Stonefoot Crash", type: "hero" },
  cid_ninja_009: { name: "Skirmisher Edge", type: "hero" },
  cid_ninja_011: { name: "Energy Thief Mari", type: "hero" },
  cid_outlander_009: { name: "Vanguard Southie", type: "hero" },
  cid_outlander_011: { name: "Gunblazer Southie", type: "hero" },
  cid_outlander_013: { name: "Fragment Flurry Jess", type: "hero" },
  hid_commando_007: { name: "Support Specialist Hawk", type: "hero" },
  hid_commando_008: { name: "Special Forces Banshee", type: "hero" },
  hid_commando_008_foundersf: { name: "Special Forces Ramirez", type: "hero" },
  hid_commando_008_foundersm: { name: "Special Forces Jonesy", type: "hero" },
  hid_commando_009: { name: "Centurion Hawk", type: "hero" },
  hid_commando_010: { name: "Sergeant Jonesy", type: "hero" },
  hid_commando_013: { name: "Demolisher Jonesy", type: "hero" },
  hid_commando_015_m_v1: { name: "Bullet Storm Jonesy", type: "hero" },
  hid_commando_gcgrenade: { name: "Commando Spitfire", type: "hero" },
  hid_commando_grenadegun: { name: "Rescue Trooper Ramirez", type: "hero" },
  hid_commando_grenadegun_m: { name: "Rescue Trooper Havoc", type: "hero" },
  hid_commando_grenademaster: {
    name: "Master Grenadier Ramirez",
    type: "hero",
  },
  hid_commando_gunheadshot_starter: {
    name: "Rogue Agent Jonesy",
    type: "hero",
  },
  hid_commando_gunheadshot: { name: "Urban Assault Headhunter", type: "hero" },
  hid_commando_guntough: { name: "Survivalist Jonesy", type: "hero" },
  hid_constructor_007: { name: "Controller Harper", type: "hero" },
  hid_constructor_007hw: { name: "Kyle the 13th", type: "hero" },
  hid_constructor_008: { name: "Power B.A.S.E. Knox", type: "hero" },
  hid_constructor_basebig: { name: "MEGA B.A.S.E. Kyle", type: "hero" },
  hid_constructor_basehyper: { name: "Hotfixer Hazard", type: "hero" },
  hid_constructor_basehyperhw: { name: "Catstructor Penny", type: "hero" },
  hid_constructor_hammerplasma: { name: "Electro-pulse Penny", type: "hero" },
  hid_constructor_hammerplasma_4thjuly: { name: "Patriot Penny", type: "hero" },
  hid_constructor_hammertank: { name: "Tank Penny", type: "hero" },
  hid_constructor_myth02: { name: "Steel Wool Syd", type: "hero" },
  hid_constructor_plasmadamage: {
    name: "Plasma Specialist Izza",
    type: "hero",
  },
  hid_constructor_plasmadamage_easter: {
    name: "Miss Bunny Penny",
    type: "hero",
  },
  hid_constructor_rushbase: { name: "Marathon Hype", type: "hero" },
  hid_ninja_010: { name: "Deadly Blade Crash", type: "hero" },
  hid_ninja_014: { name: "Thunderstrike Mari", type: "hero" },
  hid_ninja_015_f_v1: { name: "Harvester Sarah", type: "hero" },
  hid_ninja_016_f_v1: { name: "Deadly Lotus Luna", type: "hero" },
  hid_ninja_016_m_v1: { name: "Piercing Lotus Edge", type: "hero" },
  hid_ninja_slashbreath: { name: "Dragon Scorch", type: "hero" },
  hid_ninja_slashbreathhw: { name: "Sarah Hotep", type: "hero" },
  hid_ninja_slashtail: { name: "Fleetfoot Ken", type: "hero" },
  hid_ninja_smokedimmak: { name: "Dim Mak Mari", type: "hero" },
  hid_ninja_starsassassin: { name: "Assassin Sarah", type: "hero" },
  hid_ninja_starsrain: { name: "Shuriken Master Sarah", type: "hero" },
  hid_ninja_starsrainhw: { name: "Swift Shuriken Llamurai", type: "hero" },
  hid_ninja_swordmaster: { name: "Swordmaster Ken", type: "hero" },
  hid_outlander_007: { name: "Enforcer Grizzly", type: "hero" },
  hid_outlander_008: { name: "Recon Scout Eagle Eye", type: "hero" },
  hid_outlander_008_foundersf: { name: "Recon Scout Jess", type: "hero" },
  hid_outlander_008_foundersm: { name: "Recon Scout A.C.", type: "hero" },
  hid_outlander_010: { name: "Trailblaster A.C.", type: "hero" },
  hid_outlander_010_m_4thjuly: { name: "Old Glory A.C.", type: "hero" },
  hid_outlander_014: { name: "Flash A.C.", type: "hero" },
  hid_outlander_015_f_v1: { name: "T.E.D.D. Shot Jess", type: "hero" },
  hid_outlander_016_f_v1: { name: "Ambush Buzz", type: "hero" },
  hid_outlander_016_m_v1: { name: "Shockgunner Grizzly", type: "hero" },
  hid_outlander_017_m_v1: { name: "Wild Fragment Deadeye", type: "hero" },
  hid_outlander_punchdamage: { name: "Striker A.C.", type: "hero" },
  hid_outlander_punchphase: { name: "Shock Specialist A.C.", type: "hero" },
  hid_outlander_sony: { name: "Trailblazer A.C.", type: "hero" },
  hid_outlander_spherefragment: { name: "Trailblazer Quinn", type: "hero" },
  hid_outlander_xbox: { name: "Trailblazer Jess", type: "hero" },
  hid_outlander_zonefragment: { name: "Phase Scout Jess", type: "hero" },
  hid_outlander_zoneharvest: { name: "Pathfinder Jess", type: "hero" },
  hid_outlander_zoneharvesthw: { name: "Bloodfinder A.C.", type: "hero" },
  hid_outlander_zonepistol: { name: "Ranger Deadeye", type: "hero" },
};

// --- Weapon Mappings ---

export const WEAPON_MAP: Record<string, ResourceInfo> = {
  sid_assault_auto_vt: { name: "Vindertech Pulsar", type: "weapon" },
  sid_assault_bone: { name: "Primal Rifle", type: "weapon" },
  sid_assault_boombox: { name: "Beat Blaster", type: "weapon" },
  sid_assault_burst: { name: "Razor", type: "weapon" },
  sid_assault_burst_retroscifi: { name: "Gammatron 9000", type: "weapon" },
  sid_assault_doubleshot: { name: "Ranger", type: "weapon" },
  sid_assault_dragon: { name: "Dragon's Roar", type: "weapon" },
  sid_assault_fleming: { name: "The Grunt", type: "weapon" },
  sid_assault_hydra: { name: "Hydra", type: "weapon" },
  sid_assault_hydraulic_drum: { name: "Nailer", type: "weapon" },
  sid_assault_lmg: { name: "Terminator", type: "weapon" },
  sid_assault_neonglow: { name: "Argon Assault Rifle", type: "weapon" },
  sid_assault_neonglow_lmg: { name: "Mercury LMG", type: "weapon" },
  sid_assault_ratrod_autodrum: { name: "Swan", type: "weapon" },
  sid_assault_ratrod_slug: { name: "Rat King", type: "weapon" },
  sid_assault_raygun: { name: "Deathray", type: "weapon" },
  sid_assault_smg_invasion_raygun: { name: "Shooting Star", type: "weapon" },
  sid_assault_smg_silenced_military: {
    name: "Silenced Specter",
    type: "weapon",
  },
  sid_assault_smg_unsilenced_military: { name: "Specter", type: "weapon" },
  sid_assault_scavenger: { name: "Buzzcut", type: "weapon" },
  sid_assault_semiauto: { name: "Predator", type: "weapon" },
  sid_assault_singleshot: { name: "Hammercrush", type: "weapon" },
  sid_assault_singleshot_blackmetal: { name: "Blackout", type: "weapon" },
  sid_assault_steampunk_drum: { name: "Duet", type: "weapon" },
  sid_assault_surgical: { name: "Deathstalker", type: "weapon" },
  sid_assault_vacuumtube: { name: "Vacuum Tube Rifle", type: "weapon" },
  sid_assault_winter: { name: "Pain Train", type: "weapon" },
  sid_blunt_boxing_glove_club: { name: "The Contender", type: "weapon" },
  sid_blunt_club_light: { name: "Masters Driver", type: "weapon" },
  sid_blunt_hammer_artdeco: { name: "The Heavyweight", type: "weapon" },
  sid_blunt_hammer_heavy: { name: "Heavy Sledge", type: "weapon" },
  sid_blunt_hammer_heavy_dragon: { name: "Dragon's Fist", type: "weapon" },
  sid_blunt_hammer_hydraulic: { name: "Pulverizer", type: "weapon" },
  sid_blunt_hammer_medieval: { name: "Smasher Basher", type: "weapon" },
  sid_blunt_hammer_rocket: { name: "Husk Stomper", type: "weapon" },
  sid_blunt_hammer_rocket_vt: { name: "Vindertech Slammer", type: "weapon" },
  sid_blunt_heavy_paddle: { name: "The Initiator", type: "weapon" },
  sid_blunt_light: { name: "Mighty Driver", type: "weapon" },
  sid_blunt_light_bat: { name: "Mighty Slugger", type: "weapon" },
  sid_blunt_light_boombox: { name: "Mic Drop", type: "weapon" },
  sid_blunt_light_rocketbat: {
    name: "Fortsville Slugger 3000",
    type: "weapon",
  },
  sid_blunt_medium: { name: "Heavy Wrench", type: "weapon" },
  sid_blunt_medium_ratrod: { name: "Drifter", type: "weapon" },
  sid_blunt_scavenger: { name: "Pipe Down!", type: "weapon" },
  sid_blunt_tool_light: { name: "Breaching Bar", type: "weapon" },
  sid_edged_airplane_axe: { name: "Supersonic Slasher", type: "weapon" },
  sid_edged_axe_heavy: { name: "Greataxe", type: "weapon" },
  sid_edged_axe_heavy_vacuumtube: { name: "Vacuum Tube Axe", type: "weapon" },
  sid_edged_axe_light: { name: "Ski Cleaver", type: "weapon" },
  sid_edged_axe_light_ratrod: { name: "Axle", type: "weapon" },
  sid_edged_axe_medieval: { name: "Wicked Wind", type: "weapon" },
  sid_edged_axe_medium: { name: "Splinter Axe", type: "weapon" },
  sid_edged_axe_medium_laser: { name: "Armaggeddon", type: "weapon" },
  sid_edged_axe_neonglow: { name: "Argon Axe", type: "weapon" },
  sid_edged_axe_scavenger: { name: "Hack Axe", type: "weapon" },
  sid_edged_axe_vt: { name: "Vindertech Sever", type: "weapon" },
  sid_edged_scythe: { name: "Reaver", type: "weapon" },
  sid_edged_scythe_blackmetal: { name: "Brood Slicer", type: "weapon" },
  sid_edged_scythe_flintlock: { name: "Fishing Hook", type: "weapon" },
  sid_edged_scythe_laser: { name: "Reaper Scythe", type: "weapon" },
  sid_edged_scythe_neonglow: { name: "Neon Scythe", type: "weapon" },
  sid_edged_sword_hydraulic: { name: "Pressure Cutter", type: "weapon" },
  sid_edged_sword_light: { name: "Shortblade", type: "weapon" },
  sid_edged_sword_light_founders: {
    name: "Founder's Nightcleave",
    type: "weapon",
  },
  sid_edged_sword_medieval: { name: "Guardian's Will", type: "weapon" },
  sid_edged_sword_medium: { name: "Shadow Blade", type: "weapon" },
  sid_edged_sword_medium_vt: { name: "Vindertech Slicer", type: "weapon" },
  sid_edged_sword_medium_vacuumtube: {
    name: "Vacuum Tube Sword",
    type: "weapon",
  },
  sid_edged_sword_neonglow: { name: "Krypton Sword", type: "weapon" },
  sid_launcher_grenade: { name: "Thumper", type: "weapon" },
  sid_launcher_grenade_easter: { name: "Easter Egg Launcher", type: "weapon" },
  sid_launcher_hydraulic: { name: "Dam Buster", type: "weapon" },
  sid_launcher_pumpkin_rpg: { name: "Jack-O-Launcher", type: "weapon" },
  sid_launcher_rocket: { name: "Bazooka", type: "weapon" },
  sid_launcher_rocket_dragon: { name: "Dragon's Fury", type: "weapon" },
  sid_launcher_scavenger: { name: "Trash Cannon", type: "weapon" },
  sid_launcher_vacuumtube: { name: "Vacuum Tube Launcher", type: "weapon" },
  sid_launcher_wintergrenade: { name: "Snowball Launcher", type: "weapon" },
  sid_ob_assault_auto: { name: "Assault Rifle", type: "weapon" },
  sid_piercing_junkyard: { name: "Scrapper Spear", type: "weapon" },
  sid_piercing_spear: { name: "Mighty Pitchfork", type: "weapon" },
  sid_piercing_spear_blackmetal: { name: "Nightfall", type: "weapon" },
  sid_piercing_spear_hydraulic: { name: "Sawtooth", type: "weapon" },
  sid_piercing_spear_laser: { name: "Farmer's Glory", type: "weapon" },
  sid_piercing_spear_military: { name: "Dissector", type: "weapon" },
  sid_piercing_spear_scavenger: { name: "Head Clipper", type: "weapon" },
  sid_piercing_spear_steampunk: { name: "Steam Skewer", type: "weapon" },
  sid_piercing_spear_vacuumtube: { name: "Vacuum Tube Spear", type: "weapon" },
  sid_pistol_artdeco: { name: "The Mouth Piece", type: "weapon" },
  sid_pistol_auto: { name: "Viper", type: "weapon" },
  sid_pistol_autoheavy: { name: "Thrasher", type: "weapon" },
  sid_pistol_autoheavy_vt: { name: "Vindertech Blazer", type: "weapon" },
  sid_pistol_auto_vacuumtube: { name: "Lightning Pistol", type: "weapon" },
  sid_pistol_bolt: { name: "Bolt Bolt", type: "weapon" },
  sid_pistol_boltrevolver: { name: "Junkyard Pal", type: "weapon" },
  sid_pistol_bone_pistol: { name: "Primal Pistol", type: "weapon" },
  sid_pistol_boombox: { name: "Hot Mix", type: "weapon" },
  sid_pistol_dragon: { name: "Dragon's Breath", type: "weapon" },
  sid_pistol_dual: { name: "Dual Pistols", type: "weapon" },
  sid_pistol_firecracker: { name: "Freedom's Herald", type: "weapon" },
  sid_pistol_fleming_scoped: { name: "The Cyclops", type: "weapon" },
  sid_pistol_fleming_tactical: { name: "The Turncoat", type: "weapon" },
  sid_pistol_flintlock: { name: "Duelist", type: "weapon" },
  sid_pistol_gatling: { name: "Monsoon", type: "weapon" },
  sid_pistol_halloween_handcannon: { name: "Ghost Pistol", type: "weapon" },
  sid_pistol_handcannon: { name: "Judge", type: "weapon" },
  sid_pistol_handcannon_de: { name: "Bald Eagle", type: "weapon" },
  sid_pistol_handcannon_semi: { name: "Falcon", type: "weapon" },
  sid_pistol_handcannon_semi_vt: { name: "Vindertech Burster", type: "weapon" },
  sid_pistol_handcannon_vt: { name: "Vindertech Blaster", type: "weapon" },
  sid_pistol_hydraulic: { name: "Piston Spitter", type: "weapon" },
  sid_pistol_medieval: { name: "Basilisk", type: "weapon" },
  sid_pistol_neonglow: { name: "Krypton Pistol", type: "weapon" },
  sid_pistol_paper_airplane: { name: "The Paper Shredder", type: "weapon" },
  sid_pistol_rapid: { name: "Haywire Storm", type: "weapon" },
  sid_pistol_ratrod: { name: "Ratatat", type: "weapon" },
  sid_pistol_revolver_singleaction: { name: "Last Word", type: "weapon" },
  sid_pistol_rocket: { name: "Tiny Instrument of Death", type: "weapon" },
  sid_pistol_scavenger: { name: "Riptide", type: "weapon" },
  sid_pistol_semiauto: { name: "Vigilante", type: "weapon" },
  sid_pistol_silenced_christmas: { name: "Cocoa .45", type: "weapon" },
  sid_pistol_silenced_military: { name: "Whisper .45", type: "weapon" },
  sid_pistol_sixshooter: { name: "Nighthawk", type: "weapon" },
  sid_pistol_space: { name: "Space Invader", type: "weapon" },
  sid_pistol_steampunk: { name: "Steamroller", type: "weapon" },
  sid_pistol_vacuumtube_revolver: {
    name: "Vacuum Tube Revolver",
    type: "weapon",
  },
  sid_pistol_winter_gingerbread: { name: "Ginger Blaster", type: "weapon" },
  sid_pistol_zapper: { name: "Zap Zapp", type: "weapon" },
  sid_smg_fleming_burstfire: { name: "The Trinity", type: "weapon" },
  sid_smg_fleming_sidefeed: { name: "The Pepper Sprayer", type: "weapon" },
  sid_shotgun_auto: { name: "Tigerjaw", type: "weapon" },
  sid_shotgun_auto_founders: { name: "Founder's Bearcat", type: "weapon" },
  sid_shotgun_bone: { name: "Primal Shotgun", type: "weapon" },
  sid_shotgun_boombox_break: { name: "Woofer", type: "weapon" },
  sid_shotgun_break: { name: "Double-punch", type: "weapon" },
  sid_shotgun_break_flintlock: { name: "Dragoon", type: "weapon" },
  sid_shotgun_break_ou: { name: "Rustler", type: "weapon" },
  sid_shotgun_break_scavenger: { name: "Old Smokey", type: "weapon" },
  sid_shotgun_burst_blackmetal: { name: "Black Drum", type: "weapon" },
  sid_shotgun_dragon: { name: "Dragon's Might", type: "weapon" },
  sid_shotgun_dragon_drum: { name: "DragonFire", type: "weapon" },
  sid_shotgun_fleming: { name: "The Browbeater", type: "weapon" },
  sid_shotgun_heavy: { name: "Backbreaker", type: "weapon" },
  sid_shotgun_hydraulic: { name: "Pummeller", type: "weapon" },
  sid_shotgun_longarm: { name: "Longarm Enforcer", type: "weapon" },
  sid_shotgun_medieval: { name: "Stalwart Squire", type: "weapon" },
  sid_shotgun_military: { name: "Ground Pounder", type: "weapon" },
  sid_shotgun_minigun: { name: "Room Sweeper", type: "weapon" },
  sid_shotgun_neonglow: { name: "Helium Shotgun", type: "weapon" },
  sid_shotgun_ratrod: { name: "Two Step", type: "weapon" },
  sid_shotgun_semiauto: { name: "Stampede", type: "weapon" },
  sid_shotgun_semiauto_scavenger: { name: "Husk Buster", type: "weapon" },
  sid_shotgun_standard: { name: "Knight", type: "weapon" },
  sid_shotgun_standard_vt: { name: "Vindertech Disintegrator", type: "weapon" },
  sid_shotgun_steampunk: { name: "Double Boiler", type: "weapon" },
  sid_shotgun_tactical: { name: "Panther", type: "weapon" },
  sid_shotgun_tactical_precision: { name: "Nightclaw", type: "weapon" },
  sid_shotgun_vacuumtube: { name: "Vacuum Tube Shotgun", type: "weapon" },
  sid_sniper: { name: "Hydraulic Sniper", type: "weapon" },
  sid_sniper_amr: { name: "Zapotron", type: "weapon" },
  sid_sniper_artdeco: { name: "The Take Down", type: "weapon" },
  sid_sniper_auto: { name: "Extinguisher", type: "weapon" },
  sid_sniper_blackmetal: { name: "Midnight Stalker", type: "weapon" },
  sid_sniper_blackmetal_bow: { name: "Night Owl", type: "weapon" },
  sid_sniper_boltaction: { name: "Deadeye", type: "weapon" },
  sid_sniper_boltaction_scope: { name: "One Shot", type: "weapon" },
  sid_sniper_boombox: { name: "Crescendo", type: "weapon" },
  sid_sniper_crossbow: { name: "Heartbreaker", type: "weapon" },
  sid_sniper_crossbow_military: { name: "Crossbow", type: "weapon" },
  sid_sniper_dragon: { name: "Dragon's Claw", type: "weapon" },
  sid_sniper_explosivebow: { name: "Boom Bow", type: "weapon" },
  sid_sniper_fleming: { name: "The Cleaner", type: "weapon" },
  sid_sniper_fleming_bow: { name: "The Instigator", type: "weapon" },
  sid_sniper_flintlock: { name: "Ol' Betsy", type: "weapon" },
  sid_sniper_flintlock_bow: { name: "The Powder Keg", type: "weapon" },
  sid_sniper_flintlock_scope: { name: "Spyglass", type: "weapon" },
  sid_sniper_hydraulic: { name: "Tsunami", type: "weapon" },
  sid_sniper_hydraulic_bow: { name: "Compression Burster", type: "weapon" },
  sid_sniper_invasion_railgun: { name: "Third Rail", type: "weapon" },
  sid_sniper_medieval: { name: "Yeoman", type: "weapon" },
  sid_sniper_medieval_bow: { name: "Knightfire", type: "weapon" },
  sid_sniper_military: { name: "Obliterator", type: "weapon" },
  sid_sniper_neonglow: { name: "Neon Sniper Rifle", type: "weapon" },
  sid_sniper_neon_bow: { name: "Xenon Bow", type: "weapon" },
  sid_sniper_primal_flamebow: { name: "Primal Flame Bow", type: "weapon" },
  sid_sniper_primal_stinkbow: { name: "Primal Stink Bow", type: "weapon" },
  sid_sniper_ratrod: { name: "Crankshot", type: "weapon" },
  sid_sniper_scavenger: { name: "Sunsetter", type: "weapon" },
  sid_sniper_scavenger_bow: { name: "Scrap Shot", type: "weapon" },
  sid_sniper_shredder: { name: "Super Shredder", type: "weapon" },
  sid_sniper_standard: { name: "Stinger", type: "weapon" },
  sid_sniper_standard_scope: { name: "Scoped Dragonfly", type: "weapon" },
  sid_sniper_standard_scope_vt: { name: "Vindertech Jolter", type: "weapon" },
  sid_sniper_standard_winter: { name: "Frostbite", type: "weapon" },
  sid_sniper_steampunk: { name: "Bon Voyage", type: "weapon" },
  sid_sniper_steampunk_bow: { name: "Cloudburst", type: "weapon" },
  sid_sniper_tripleshot: { name: "Triple Tap", type: "weapon" },
  sid_sniper_vacuumtube: { name: "Vacuum Tube Sniper Rifle", type: "weapon" },
  sid_sniper_vacuumtube_bow: { name: "Vacuum Tube Bow", type: "weapon" },
  sid_sniper_valentine_bow: { name: "Love Song", type: "weapon" },
  sid_sniper_vindertech_bow: { name: "Vindertech Seeker", type: "weapon" },
  sid_testchargerocket: { name: "Test Charge Rocket", type: "weapon" },
  sid_troll_launcher_durability: { name: "Troll Launcher", type: "weapon" },
};

export const BASE_KEYS_WITH_RARITY: Set<string> = new Set([
  "workerbasic",
  "did_defender",
  "hid_ninja",
  "hid_outlander",
  "hid_soldier",
  "hid_constructor",
  "schematic:sid",
]);
// --- Global Rarity Mapping ---
export const RARITY_CODE_TO_NAME: Record<string, string> = {
  uc: "Uncommon",
  r: "Rare",
  vr: "Epic",
  sr: "Legendary",
  ur: "Mythic",
};

export const THEATER_MAP: Record<string, string> = {
  "33A2311D4AE64B361CCE27BC9F313C8B": "Stonewood",
  D477605B4FA48648107B649CE97FCF27: "Plankerton",
  E6ECBD064B153234656CB4BDE6743870: "Canny Valley",
  D9A801C5444D1C74D1B7DAB5C7C12C5B: "Twine Peaks",
  "0C92E7904E00C6C93406BB9C26ACD2B0": "Storm King's Domain",
  "394D85EF40B2BF401E6F32B587D7672B": "Dungeons",
  "21726CDB473D7BD46C9643AA71DB4C6A": "Visit the Crater",
  DB73FE4C445040F5886B5FB337BC8C83: "Horde",
  "25D86CC64F0F3EE1831CFD9B2DF6D68C": "Blasted Badlands",
  FF97186D4741CB5F2A980BB0164081D4: "Flannel Falls",
  D61659064BED28BEA91FD2A343C126B7: "Frozen Fjords",
  DBB6E92A4EDE30B76C94C7BA3852C473: "Hexsylvania",
  "243870C643F8611F25D24287814E1DA4": "Scurvy Shoals",
  "67EDCFE942260C290B369BA7AA70A0D5": "PerfMem",
  "8633333E41A86F67F78EAEAF25BF4735": "Tutorial",
};

export const THEME_MAP: Record<string, string> = {
  GhostTown: "Ghost Town",
  Route99: "Route 99",
  TheCity: "City",
  TheIndustrialPark: "Industrial Park",
  Lakeside: "Autumn Lakeside",
  TheSuburbs: "Suburban",
  ZT_TheGrasslands: "Grasslands",
  AD2_TheGrasslands: "Autumn Foothills",
  TheGrasslands: "Autumn Grassland",
  TheForest: "Forest",
  Desert_Bunker: "Desert Bunker",
  TheDesert: "Desert",
  DUDEBRO: "Portal",
  DUDEBRO_HARD: "The Portal>",
  Tropical_Water: "Water?",
  Yarrr_Island: "Pirate Cove",
  Tropical_Island: "Tropical Island",
  Plank_Island: "Pirate Plank",
  TheOutpost_PvE_01: "Stonewood Shield",
  TheOutpost_PvE_02: "Plankerton Shield",
  TheOutpost_PvE_03: "Canny Shield",
  TheOutpost_PvE_04: "Twine Shield",
  Autumn: "Autumn Foothills",
  Winter: "Winter",
  Halloween: "Hexsylvania",
  Grasslands: "Grasslands",
  Suburban: "Suburban",
  City: "City",
  Industrial: "Industrial",
  Desert: "Desert",
  "BP_ZT_TRV_SW.BP_ZT_TRV_SW_C": "Swamp",
  "BP_ZT_TRV_HF_Intro.BP_ZT_TRV_HF_Intro_C": "Haunted Forest Intro",
  "BP_ZT_TRV_HauntedHotel.BP_ZT_TRV_HauntedHotel_C": "Haunted Hotel",
  "BP_ZT_TRV_HF_CastleB.BP_ZT_TRV_HF_CastleB_C": "Haunted Castle(B)",
  "BP_ZT_TRV_HF_Castle.BP_ZT_TRV_HF_Castle_C": "Haunted Castle",
  "BP_ZT_TRV_HauntedHotel_HuskEscape.BP_ZT_TRV_HauntedHotel_HuskEscape_C":
    "Haunted Hotel Husk Escape",
  "BP_ZT_TRV_HF.BP_ZT_TRV_HF_C": "Haunted Forest",
  "BP_ZT_TRV_HauntedHotel_Replay.BP_ZT_TRV_HauntedHotel_Replay_C":
    "Haunted Hotel Replay",
  "BP_ZT_TRV_HauntedHotel_Aged.BP_ZT_TRV_HauntedHotel_Aged_C":
    "Aged Haunted Hotel",
  "BP_ZT_TRV_SlasherCamp.BP_ZT_TRV_SlasherCamp_C": "Slasher Camp",
};

export const MISSION_NAME_MAP: Record<string, string> = {
  Cat1FtS: "Fight the Storm (Category 1)",
  GateSingle: "Fight the Storm (1 Atlas)",
  "1Gate": "Fight the Storm (1 Atlas)",
  Cat2FtS: "Fight the Storm (Category 2)",
  "2Gates": "Fight the Storm (2 Atlases)",
  Cat3FtS: "Fight the Storm (Category 3)",
  "3Gates": "Fight the Storm (3 Atlases)",
  Cat4FtS: "Fight the Storm (Category 4)",
  "4Gates": "Fight the Storm (4 Atlases)",
  DtB: "Deliver the Bomb",
  DeliverTheBomb: "Deliver the Bomb",
  DtE: "Destroy the Encampments",
  DestroyTheEncampments: "Destroy the Encampments",
  EliminateAndCollect: "Eliminate and Collect",
  EtS_C: "Evacuate the Shelter",
  EtShelter: "Evacuate the Shelter",
  EvacuateTheSurvivors: "Rescue the Survivors",
  EtSurvivors: "Rescue the Survivors",
  BuildtheRadarGrid: "Build the Radar Grid",
  BuildTheRadar: "Build the Radar Grid",
  RefuelTheBase: "Refuel the Homebase",
  FuelTheHomebase: "Refuel the Homebase",
  Resupply: "Resupply",
  HTM: "Hunt The Titan",
  LtR: "Launch the Rocket",
  LaunchTheRocket: "Launch the Rocket",
  RtD: "Retrieve the Data",
  RetrieveTheData: "Retrieve the Data",
  LtB: "Ride the Lightning",
  RtL: "Ride the Lightning",
  T1_VHT_LtB: "Ride the Lightning",
  LaunchTheBalloon: "Ride the Lightning",
  RideTheLightning: "Ride the Lightning",
  RtS: "Repair the Shelter",
  PowerTheStormShield: "Repair the Shelter",
  Outpost: "Storm Shield Defense",
  SSD: "Storm Shield Defense",
  TrapTheStorm: "Trap The Storm",
  SurviveTheNight: "Survive The Night",
  HitTheRoad: "Hit The Road",
  ProtectThePresents: "Protect The Presents",
  Frostnite: "Frostnite",
  Mayday: "Mayday",
  HauntTheTitan: "Haunt The Titan",
  MiniBoss: "Mini-Boss Mission",
  Miniboss: "Mini-Boss Mission",
  DUDEBRO: "Mini-Boss: CSK?",
};

export const WORLD_POWER_LEVEL: WorldPowerLevels = {
  "33A2311D4AE64B361CCE27BC9F313C8B": {
    // Stonewood
    Start_Zone1: 1,
    Start_Zone2: 3,
    Start_Zone3: 5,
    Start_Zone4: 9,
    Start_Zone5: 15,
    Normal_Zone1: 19,
  },
  D477605B4FA48648107B649CE97FCF27: {
    // Plankerton
    Normal_Zone1: 19,
    Normal_Zone2: 23,
    Normal_Zone3: 28,
    Normal_Zone4: 34,
    Normal_Zone5: 40,
    Hard_Zone1: 46,
  },
  E6ECBD064B153234656CB4BDE6743870: {
    // Canny Valley
    Hard_Zone1: 46,
    Hard_Zone2: 52,
    Hard_Zone3: 58,
    Hard_Zone4: 64,
    Hard_Zone5: 70,
    Hard_Zone5_Dudebro: 70,
  },
  D9A801C5444D1C74D1B7DAB5C7C12C5B: {
    // Twine Peaks
    Nightmare_Zone1: 76,
    Nightmare_Zone2: 82,
    Nightmare_Zone3: 88,
    Nightmare_Zone4: 94,
    Nightmare_Zone5: 100,
    Nightmare_Zone10_Dudebro: 140,
    Endgame_Zone1: 108,
    Endgame_Zone2: 116,
    Endgame_Zone3: 124,
    Endgame_Zone4: 132,
    Endgame_Zone5: 140,
    Endgame_Zone6: 160,
  },
  "25D86CC64F0F3EE1831CFD9B2DF6D68C": {
    // Ventures
    Phoenix_Zone02: 3,
    Phoenix_Zone03: 5,
    Phoenix_Zone05: 15,
    Phoenix_Zone07: 23,
    Phoenix_Zone09: 34,
    Phoenix_Zone11: 46,
    Phoenix_Zone13: 58,
    Phoenix_Zone15: 70,
    Phoenix_Zone17: 82,
    Phoenix_Zone19: 94,
    Phoenix_Zone21: 108,
    Phoenix_Zone23: 124,
    Phoenix_Zone25: 140,
  },
};

export const ZONE_ORDER = [
  "33A2311D4AE64B361CCE27BC9F313C8B", // Stonewood
  "D477605B4FA48648107B649CE97FCF27", // Plankerton
  "E6ECBD064B153234656CB4BDE6743870", // Canny Valley
  "D9A801C5444D1C74D1B7DAB5C7C12C5B", // Twine Peaks
  "25D86CC64F0F3EE1831CFD9B2DF6D68C", // Blasted Badlands
  "DBB6E92A4EDE30B76C94C7BA3852C473", // Hexsylvania
  "FF97186D4741CB5F2A980BB0164081D4", // Flannel Falls
  "D61659064BED28BEA91FD2A343C126B7", // Frozen Fjords
  "243870C643F8611F25D24287814E1DA4", // Scurvy Shoals
];

export const MODS_MAP: Record<string, string> = {
  "GameplayModifier:minibossenableprimarymissionitem": "Miniboss",
  "GameplayModifier:elementalzonefireenableitem": "Fire Storm",
  "GameplayModifier:elementalzonenatureenableitem": "Nature Storm",
  "GameplayModifier:elementalzonewaterenableitem": "Water Storm",
  "GameplayModifier:elementalzonephysicalenableitem": "Physical Storm",
  "GameplayModifier:gm_basehusk_ondeath_explode": "Exploding Deathburst",
  "GameplayModifier:mutator_explodingdeathburst":
    "Exploding Deathburst (Alt ID)",
  "GameplayModifier:mutator_healingdeathburst": "Healing Deathburst",
  "GameplayModifier:mutator_acidpools": "Acid Pools",
  "GameplayModifier:mutator_smokescreen": "Smokescreen",
  "GameplayModifier:gm_enemy_hideonminimap": "Hidden Minimap Markers",
  "GameplayModifier:gm_enemy_ondeath_applyspeedmods": "Death Speed Boost",
  "GameplayModifier:gm_enemy_ondeath_areaheal": "Death Heal Burst",
  "GameplayModifier:gm_enemy_ondeath_spawndamagepool": "Death Pools",
  "GameplayModifier:gm_enemy_ondeath_spawnenemyrange":
    "Spawn Extra Ranged Enemies",
  "GameplayModifier:gm_enemy_ondeath_spawnplayerslow": "Player Slow Zones",
  "GameplayModifier:gm_enemy_ondmgdealt_lifeleech": "Life Leech Attacks",
  "GameplayModifier:gm_enemy_ondmgdealt_slowdownfoe": "Slowing Attacks",
  "GameplayModifier:gm_enemy_ondmgreceived_speedbuff": "Enraged When Damaged",
  "GameplayModifier:gm_enemy_onhitweakenbuildings": "Weaken Structures",
  "GameplayModifier:gm_enemy_metalcorrosion": "Metal Corrosion",
  "GameplayModifier:gm_enemy_speedaura": "Speedy Husks",
  "GameplayModifier:gm_enemy_sharedlives": "Shared Husk Health",
  "GameplayModifier:gm_enemy_tank": "Tanky Husks",
  "GameplayModifier:gm_enemy_ondmgdealt_attackspeedbuff": "Frenzied Husks",
  "GameplayModifier:gm_player_slowaura": "Slowing Pools",
  "GameplayModifier:mutator_wallweakening": "Wall Weakening",
  "GameplayModifier:gm_enemy_ondeath_spawnenemyrangeresistpool": "Smokescreen",
  "GameplayModifier:gm_basehusk_ondmgdealt_metalcorrosion": "Metal Corrosion",
  "GameplayModifier:gm_enemy_ondeath_spawnplayerslowpool": "Slowing Pools",
  "GameplayModifier:gm_constructor_buildcost_buff":
    "Constructor Build Cost Reduction",
  "GameplayModifier:gm_constructor_damage_buff": "Constructor Damage Boost",
  "GameplayModifier:gm_hero_tech_buff": "Hero Tech Boost",
  "GameplayModifier:gm_ninja_abilityrate_buff": "Ninja Ability Rate Boost",
  "GameplayModifier:gm_ninja_damage_buff": "Ninja Damage Boost",
  "GameplayModifier:gm_ninja_jumpheight_buff": "Ninja Jump Boost",
  "GameplayModifier:gm_ninja_sword_damagebuff": "Ninja Sword Damage Boost",
  "GameplayModifier:gm_outlander_damage_buff": "Outlander Damage Boost",
  "GameplayModifier:gm_outlander_tech_buff": "Outlander Tech Boost",
  "GameplayModifier:gm_player_assaultrifle_damage_buff":
    "Assault Rifle Damage Boost",
  "GameplayModifier:gm_player_axesscythesdamage_buff":
    "Axe & Scythe Damage Boost",
  "GameplayModifier:gm_player_bluntdamage_buff": "Blunt Weapon Damage Boost",
  "GameplayModifier:gm_player_energy_damagebuff": "Energy Damage Boost",
  "GameplayModifier:gm_player_explosive_damagebuff": "Explosive Damage Boost",
  "GameplayModifier:gm_player_meleeknockback_buff": "Melee Knockback Boost",
  "GameplayModifier:gm_player_ondmgdealt_lifeleech": "Life Leech (Player)",
  "GameplayModifier:gm_player_onshielddestroyed_aoe": "Shield AOE Explosion",
  "GameplayModifier:gm_player_pistol_damagebuff": "Pistol Damage Boost",
  "GameplayModifier:gm_player_shotgun_damagebuff": "Shotgun Damage Boost",
  "GameplayModifier:gm_player_smg_damage_buff": "SMG Damage Boost",
  "GameplayModifier:gm_player_sniperrifle_damagebuff": "Sniper Damage Boost",
  "GameplayModifier:gm_player_spearsworddamage_buff":
    "Spear & Sword Damage Boost",
  "GameplayModifier:gm_player_jumpheight": "Higher Jump",
  "GameplayModifier:gm_soldier_abilityrate_buff": "Soldier Ability Rate Boost",
  "GameplayModifier:gm_soldier_assaultrifle_buff": "Soldier AR Boost",
  "GameplayModifier:gm_soldier_damage_buff": "Soldier Damage Boost",
  "GameplayModifier:gm_trap_buff": "Trap Damage Boost",
  "GameplayModifier:GM_Phoenix_CloseQuarters": "Short Range",
  "GameplayModifier:GM_Phoenix_SuperConstructor": "Super Constructor",
  "GameplayModifier:GM_Phoenix_SuperHeroic": "Super Soldier",
  "GameplayModifier:GM_Phoenix_SuperNinja": "Super Ninja",
  "GameplayModifier:GM_Phoenix_SuperOutlander": "Super Outlander",
  "GameplayModifier:gm_player_abilitiesdisabled": "Abilities Disabled",
  "GameplayModifier:mutator_unpartychampions": "Uncharted Enemies",
};
